/* Write your T-SQL query statement below */
SELECT USERS.NAME, SUM(TRANSACTIONS.AMOUNT) AS [BALANCE]
FROM USERS
JOIN
TRANSACTIONS
ON 
USERS.ACCOUNT = TRANSACTIONS.ACCOUNT
GROUP BY USERS.NAME
HAVING SUM(TRANSACTIONS.AMOUNT) > 10000;